name: helpcare
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  animate_do: ^3.3.4
  easy_localization: ^3.0.0
  dotted_border: ^2.1.0
  audio_wave: ^0.1.4
  google_maps_flutter: ^2.1.12
  flutter_launcher_icons: ^0.14.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.png"
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Gilroy-Medium
      fonts: 
        - asset: assets/fonts/Gilroy-Medium.ttf
          
